theme: jekyll-theme-cayman
title: Hello.
description: I'm Corey, an undergrad student at the University of Scranton pursuing my bachelors degree in IT. I'm currently seeking an internship.
author: Corey Walsh
